services:
  thesis-container:
    build:
      context: .        
      dockerfile: Dockerfile
    image: thesis  
    container_name: thesis_container
    volumes:
      - .:/thesis
    working_dir: /thesis
    command: ["make"]
    # command: >
    #   /bin/bash -c "make && tail -f /dev/null"
    stdin_open: true
    tty: true